### ISSUE TITLE
this one won't compile for me -- fedora 30

### ISSUE THREAD

**Issue by rikmnet** [archphile/mpd-manisiutkin#3]
...is there any intention to get this patch included in mainline mpd?  It's certainly useful and seems to have been stable for a while now... Fedora 30 is actually at the current mpd 21.9 release but I can't get the mainline src or your patched version of 22beta to compile...I suspect a Debian vs. Redhat thing is going on

In any case, as I said the compile stops early in the process:

In file included from ../../src/event/ServerSocket.cxx:22:
../../src/net/IPv4Address.hxx: In member function ‘constexpr IPv4Address::operator SocketAddress() const’:

../../src/net/IPv4Address.hxx:171:24: error: a reinterpret_cast is not a constant expression
  171 |   return SocketAddress((const struct sockaddr *)&address,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from ../../src/event/ServerSocket.cxx:23:
../../src/net/IPv6Address.hxx: In member function ‘constexpr IPv6Address::operator SocketAddress() const’:

../../src/net/IPv6Address.hxx:138:24: error: a reinterpret_cast is not a constant expression
  138 |   return SocketAddress((const struct sockaddr *)&address,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[72/660] Compiling C++ object 'src/lib/dbus/c436a3e@@dbus@sta/Watch.cxx.o'.
ninja: build stopped: subcommand failed.

---

thanks and any help appreciated

**Comment by archphile** [comment]
This code is not mine. I just get it from:

https://sourceforge.net/p/sacddecoder/mpd/MPD.git/ci/master/tree/

and push it here so that we have a backup.

You can contact the patch creator for further details:

https://sourceforge.net/u/manisiutkin/profile/

I also got issues from time to time when compiling with latest code, this is why I decided to use the latest commit used in this package, that usually works:

https://aur.archlinux.org/packages/mpd-sacd/

If you see the PKGBUILD, they still use the following source:

https://git.code.sf.net/p/sacddecoder/mpd/MPD.git#commit=fad7f5c0627b4f4f91adec35a8a7f5569a62de09
